### ISSUE TITLE
Merge with toxcore through patches

### ISSUE THREAD

**Issue by ddobrev** [kpp/2tox#12]
Hello,

I read your article at https://habrahabr.ru/post/276665/ . I saw your pull request has been taken so I would like to ask why you have started a new project. We all know that forking is the worst and therefore last feasible option because it leads to duplicated effort instead of making a single code base stronger.

**Comment by suhr** [comment]
This project is not a fork, it's an alternative implementation. And there's two things to consider:
- There's no specification on Tox protocol, and toxcore developers don't seem going to write one. But since this project have to investigate how tox actually works, the chance the spec will ever be written is higher.
- C is not a language you can easily write safe code with.

**Comment by ddobrev** [comment]
@suhr I understand. Would existing Tox clients, such as qTox (https://github.com/tux3/qTox), be compatible with your implementation?

**Comment by kpp** [comment]
@ddobrev Yes. Have a look at project goals in the new version of [README.md](https://github.com/kpp/2tox/blob/master/README.md)

**Comment by ddobrev** [comment]
@kpp Thank you for your answer, all clear.
While I am still convinced you'd better direct your effort towards toxcore - its developers do need help - I understand it's your decision. Please consider my question answered and the issue therefore closed.
